<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Login</name>
   <tag></tag>
   <elementGuidId>515b0841-3d4c-4af5-9c1f-1cf69b2c3656</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='gatsby-focus-wrapper']/div/nav/div/div/div/div/ul/li[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>9aa60a05-c218-4f5f-b5fd-1317446a668e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex flex-row py-2 pl-3 pr-4 no-underline rounded md:bg-transparent md:p-0 text-white items-center visited:text-white</value>
      <webElementGuid>4139c33c-4c68-4161-8951-1e438d7ac877</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/login</value>
      <webElementGuid>bfb58085-af9b-4c48-a82c-f9a3c09c44f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login</value>
      <webElementGuid>ae8e3ab3-52c7-4046-883f-5393548e6df9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gatsby-focus-wrapper&quot;)/div[1]/nav[@class=&quot;border-gray-200 px-2 sm:px-4 py-2.5 mb-24 rounded dark:bg-gray-900 bg-sepirak-link w-full&quot;]/div[1]/div[1]/div[@class=&quot;md:flex md:flex-wrap md:items-center md:justify-between sm:relative&quot;]/div[@class=&quot;flex md:order-2 sm:flex-nowrap&quot;]/ul[@class=&quot;md:flex p-4 m-0 md:flex-row md:space-x-8 md:mt-0 md:text-medium md:font-medium sm:flex-row&quot;]/li[@class=&quot;m-0 my-auto&quot;]/a[@class=&quot;flex flex-row py-2 pl-3 pr-4 no-underline rounded md:bg-transparent md:p-0 text-white items-center visited:text-white&quot;]</value>
      <webElementGuid>e453aec7-a3b7-4988-83c5-08e2302ca3b1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gatsby-focus-wrapper']/div/nav/div/div/div/div/ul/li[2]/a</value>
      <webElementGuid>d86d17b1-c5a5-4e4b-b6f9-a1a9dc787678</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Login')]</value>
      <webElementGuid>c8227491-5d8e-476a-802d-ccc937c74a15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign up'])[1]/following::a[1]</value>
      <webElementGuid>490475db-83d7-4ba8-82e4-8e071b0c5080</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=')'])[1]/following::a[2]</value>
      <webElementGuid>97f4420a-34a6-4eb9-9f9e-853f7f253816</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/preceding::a[1]</value>
      <webElementGuid>ef70ca06-acc7-4a34-a138-ef20ceb9d9f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pricing'])[1]/preceding::a[2]</value>
      <webElementGuid>efbf24b2-db1c-4b04-9129-4d32ad18dab0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Login']/parent::*</value>
      <webElementGuid>92440fc9-954f-4797-ada2-0d9de4573969</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/login')]</value>
      <webElementGuid>e2573c78-8c95-46ca-9935-66e294ab9ba9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a</value>
      <webElementGuid>6f287c5d-2e92-4928-81f2-27828892486a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/login' and (text() = 'Login' or . = 'Login')]</value>
      <webElementGuid>bf260c9f-637b-4d35-8e37-575763b9da2f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
